// Generates social-preview images.
//
// Why: every cover on this site is WebP. Facebook and X render WebP previews,
// but LinkedIn and WhatsApp do not — a shared product, project or article link
// showed up as a bare link with no image. Social crawlers are also happiest
// with a fixed 1200x630, which lets og:image:width/height be honest.
//
// So each source cover gets a 1200x630 JPEG under public/og/, and
// lib/og-manifest.ts records which sources have one (pageMetadata falls back
// to the default card for anything not listed).
//
//   node scripts/generate-og.mjs          regenerate missing
//   node scripts/generate-og.mjs --force  rebuild all
//
// Re-run after adding a product photo, project, article or district cover.

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFile, writeFile, mkdir, access } from 'node:fs/promises';
import path from 'node:path';

const run = promisify(execFile);
const ROOT = path.resolve(import.meta.dirname, '..');
const PUB = path.join(ROOT, 'public');
const OUT = path.join(PUB, 'og');
const W = 1200, H = 630;
const force = process.argv.includes('--force');

const read = (p) => readFile(path.join(ROOT, p), 'utf8');
const exists = (p) => access(p).then(() => true, () => false);

/** Every image the site hands to pageMetadata as a social card. */
async function sources() {
  const out = new Set();
  const cat = await read('content/catalogue.ts');
  // PHOTO_SLUGS drives productPhoto(); only those slugs have a file on disk
  const photoBlock = cat.slice(cat.indexOf('PHOTO_SLUGS'), cat.indexOf('PHOTO_OVERRIDES'));
  for (const m of photoBlock.matchAll(/'([a-z0-9-]+)'/g)) out.add(`/products/${m[1]}.webp`);
  // A handful of products point at a differently-named file; mirror productPhoto()
  const ov = cat.slice(cat.indexOf('PHOTO_OVERRIDES'), cat.indexOf('export const productPhoto'));
  for (const m of ov.matchAll(/'([a-z0-9-]+)':\s*'([^']+)'/g)) {
    out.delete(`/products/${m[1]}.webp`);
    out.add(m[2]);
  }

  for (const f of ['content/projects.ts', 'content/blog.ts', 'content/districts.ts']) {
    const src = await read(f);
    for (const m of src.matchAll(/cover:\s*'([^']+)'/g)) out.add(m[1]);
    for (const m of src.matchAll(/"cover":\s*"([^"]+)"/g)) out.add(m[1]);
  }
  return [...out].sort();
}

/** /products/x.webp -> og/products-x.jpg */
const flat = (src) => src.replace(/^\//, '').replace(/\//g, '-').replace(/\.\w+$/, '') + '.jpg';

async function convert(src) {
  const from = path.join(PUB, src.replace(/^\//, ''));
  if (!(await exists(from))) return { src, skipped: 'kaynak yok' };
  const to = path.join(OUT, flat(src));
  if (!force && (await exists(to))) return { src, skipped: 'mevcut' };
  // Fill the whole card, centre-cropping the overflow — these are photographs,
  // so a crop reads better than letterbox bars.
  await run('ffmpeg', [
    '-y', '-loglevel', 'error', '-i', from,
    '-vf', `scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H}`,
    '-q:v', '4', to,
  ]);
  return { src, ok: true };
}

const list = await sources();
await mkdir(OUT, { recursive: true });
const results = await Promise.all(list.map(convert));

const made = results.filter((r) => r.ok).length;
const kept = results.filter((r) => r.skipped === 'mevcut').length;
const missing = results.filter((r) => r.skipped === 'kaynak yok');
const covered = results.filter((r) => r.ok || r.skipped === 'mevcut').map((r) => r.src);

await writeFile(
  path.join(ROOT, 'lib/og-manifest.ts'),
  `// GENERATED by scripts/generate-og.mjs — do not edit by hand.\n` +
    `// Source covers that have a 1200x630 JPEG social card under /public/og.\n` +
    `export const OG_SOURCES = new Set<string>([\n` +
    covered.map((s) => `  '${s}',`).join('\n') +
    `\n]);\n`,
  'utf8',
);

console.log(`og: ${made} üretildi, ${kept} mevcut, ${covered.length} kayıtlı`);
if (missing.length) console.log('kaynağı olmayan:', missing.map((m) => m.src).join(', '));
